<!doctype html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>Exceptions</title>
  <meta name="generator" content="CherryTree">
  <link rel="stylesheet" href="res/styles4.css" type="text/css" />
</head>
<body>
<div class='page'><h1 class='title'>Exceptions</h1><br/><br />When an error occur, Ruby raises an exception. Normally when an exception is raised, the program terminates its execution.<br />Ruby, like almost all OO languages, allows us to handle the error and execute some arbitrary code<br />Exception in Ruby are object instances of the Exception class (or one of its subclasses)<br /><a href=""><img src="images/1793-1.png" alt="images/1793-1.png" /></a><br /><br /><br /><strong>rescue</strong><br />If we want to handle an exception and execute some arbitrary code when it happens, you can use rescue.<br /><div class="codebox"><pre><span style="color:#ff9d00;font-weight:700">def</span> fact(n)<br />	<span style="color:#ff9d00;font-weight:700">return</span> <span style="color:#ff0044;font-weight:400">1</span> <span style="color:#ff9d00;font-weight:700">if</span> n==<span style="color:#ff0044;font-weight:400">0</span><br />	<span style="color:#ff9d00;font-weight:700">return</span> <span style="color:#ff0044;font-weight:400">1</span> <span style="color:#ff9d00;font-weight:700">if</span> n==<span style="color:#ff0044;font-weight:400">1</span><br />	n*fact(n-<span style="color:#ff0044;font-weight:400">1</span>)<br /><span style="color:#ff9d00;font-weight:700">end</span><br /><br /><span style="color:#ff9d00;font-weight:700">begin</span><br />	a=fact(<span style="color:#7f0044;font-weight:400">ARGV</span>[<span style="color:#ff0044;font-weight:400">0</span>].to_i)<br />	p a<br /><span style="color:#ff9d00;font-weight:700">rescue</span><br />	p <span style="color:#333333;font-weight:400">$!</span>.message<br /><span style="color:#ff9d00;font-weight:700">end</span></pre></div><br />    p() is a Kernel method. It writes obj.inspect to the standard output.<br />    In Ruby, $! refers the last Exception object.<br />    <a href=""><img src="images/1793-2.png" alt="images/1793-2.png" /></a><br /><br /><strong>retry</strong><br />Retry is a clause that can be used inside a rescue clause to re-execute the block of code that has caused the exception<br /><span style="text-decoration:underline;">Attention</span>: with retry, you might introduce an infinite loop of retry block execution. <br /><span style="color:#a5452a;">example:</span><br />When b is 0, a ZeroDivisionError occurs. Rescue captures it, changes b to 1 and then retry the begin block.<br /><div class="codebox"><pre>a=<span style="color:#7f0044;font-weight:400">ARGV</span>[<span style="color:#ff0044;font-weight:400">0</span>].to_i<br />b=<span style="color:#7f0044;font-weight:400">ARGV</span>[<span style="color:#ff0044;font-weight:400">1</span>].to_i<br /><br /><span style="color:#ff9d00;font-weight:700">begin</span><br /> print <span style="color:#3ad900;font-weight:400">&quot;#{a} / #{b} = &quot;</span><br /> print a/b, <span style="color:#3ad900;font-weight:400">&quot;\n&quot;</span><br /><span style="color:#ff9d00;font-weight:700">rescue</span><br /> print <span style="color:#3ad900;font-weight:400">&quot;Error\n&quot;</span><br /> b=<span style="color:#ff0044;font-weight:400">1</span><br /> <span style="color:#ff9d00;font-weight:700">retry</span><br /><span style="color:#ff9d00;font-weight:700">end</span></pre></div><br />    <a href=""><img src="images/1793-3.png" alt="images/1793-3.png" /></a><br /><br /></div>
</body>
</html>
